# SPDX-License-Identifier: MIT

version: "3"
services:
    pds-gosec:
        build:
            args:
                - BASE_IMAGE=debian:11-slim
            context: docker/
            dockerfile: GoSec-Debian.dockerfile
        container_name: pds-gosec
        hostname: pds-gosec
        env_file:
            - .env
        networks:
            - "sechub"
        volumes:
          - ./docker/scripts:/scripts

networks:
    sechub:
        external: true
        name: "sechub"
