# SPDX-License-Identifier: MIT

version: "3"
services:
    pds-findsecuritybugs-ubuntu:
        build:
            args:
                - BASE_IMAGE=ubuntu:20.04
            context: docker/
            dockerfile: FindSecurityBugs-Ubuntu.dockerfile
        container_name: pds-findsecuritybugs-ubuntu
        env_file:
            - .env
        networks:
            - "sechub"

networks:
    sechub:
        external: true
        name: "sechub"
