# SPDX-License-Identifier: MIT

version: "3"
services:
    pds:
        build:
            args:
                - BASE_IMAGE=debian:11-slim
                - BUILD_TYPE=download
                - PDS_VERSION=${PDS_VERSION}
            context: docker/
            dockerfile: PDS-Debian.dockerfile
        container_name: pds
        env_file:
            - .env
        ports:
            - "127.0.0.1:8444:8444"
            - "127.0.0.1:15024:15024"
        networks:
            - "internal"
        volumes:
          - ./docker/scripts:/scripts
          - ./docker/mocks:/mocks
networks:
    internal:
