// SPDX-License-Identifier: MIT

== GitHub Action for SecHub scan

This GitHub action uses the SecHub cli to scan the repository for security issues.


=== Usage

To be able to use this action you need a SecHub project. Check the https://mercedes-benz.github.io/sechub/[documentation] on how to set one up.

```yaml

- uses: mercedes-benz/sechub/github-actions/scan@latest
  with:
    # OPTIONAL: Path to sechub.json for manual configuration. If no value is set the input parameters will be used to create it for the scan.'
    config-path: 'sechub.json'

    # OPTIONAL: SecHub server url
    url: ${{ secrets.SECHUB_SERVER }}

    # OPTIONAL: SecHub api token
    api-token: ${{ secrets.SECHUB_APITOKEN }}

    # OPTIONAL: SecHub user
    user: ${{ secrets.SECHUB_USERID }}

    # OPTIONAL: the name of the project registered in SecHub (required if config-path not set)
    project-name: ${{ secrets.SECHUB_PROJECT }}

    # OPTIONAL: Which version of the SecHub cli to use
    # DEFAULT: 1.2.0
    version: '1.2.0'

    # OPTIONAL: A list of folders to be included. Multiple folders can be separated by ,
    include-folders: 'src,lib,config'

    # OPTIONAL: A list of folders to be excluded. Multiple folders can be separated by ,
    # DEFAULT: empty (see SecHub documentation for default excludes)
    exclude-folders: 'bin,build,dist,logs'

    # REQUIRED: The formats in which the report should be downloaded. Multiple values can be separatd by ,
    # DEFAULT: json,html
    report-formats: 'json,html'

    # OPTIONAL: SecHub debug output on/off.
    # DEFAULT: false
    debug: false

    # OPTIONAL: job (pipeline) will be marked as failed if sechub finds something
    # DEFAULT: true
    fail-job-with-findings: false
----

=== Outputs

The following table lists the output variables available after this SecHub GitHub Action has completed:

[cols="20%,40%,40%"]
|===
| Output Name          | Description                                           | Expected Values
|---------------------|-------------------------------------------------------|--------------------------------------------------

| scan-trafficlight    | Provides the color of the traffic light reported by SecHub if the scan ran successfully. If the scan fails, the value will be `FAILURE`. | Expected values: `GREEN`, `YELLOW`, `RED`, or `FAILURE`.
| scan-findings-count  | Represents the total number of findings reported by SecHub. If the scan doesn't complete, the value will be 0. | Expected value: 0
| scan-findings-high   | Indicates the number of high-level findings reported by SecHub. | Expected value: 0
| scan-findings-medium | Represents the number of medium-level findings reported by SecHub. | Expected value: 0
| scan-findings-low    | Denotes the number of low-level findings reported by SecHub. | Expected value: 0
| scan-readable-summary| Offers a human-readable summary of the scan outcome, including the traffic light color, findings count, and their distribution. If an error occurs, it will indicate that the scan could not be executed. Otherwise, it will provide detailed information such as the reported traffic light color, the number of findings, and their distribution. | Expected values: For example, `SecHub scan could not be executed` if an error occurred. Otherwise, `SecHub reported traffic light color YELLOW with 15 findings, categorized as follows: MEDIUM (8), LOW (7)`

|===


The output variables can be accessed after the action has run using the syntax `${{ steps.<step-id>.outputs.<output-name> }}`

=== Build

To build the action locally you have to run this command:

[source,npm]
----
npm run build
----

This will run the `ncc` compiler and transpile the files from the src folder into the files from the dist folder.
The dist files will be executed by the GitHub Action.

It's necessary to execute the build after every change of the sources and you have to commit the changes in dist to git.

=== Test

To run the tests you have to run this command:

[source,npm]
----
npm run test
----
