# SPDX-License-Identifier: MIT

version: "3"
services:
    sechub:
        build:
            args:
                - BASE_IMAGE=debian:11-slim
                - BUILD_TYPE=${BUILD_TYPE}
            context: docker/
            dockerfile: SecHub-Debian.dockerfile
        container_name: sechub
        hostname: sechub
        env_file:
            - .env
            - .env-single
        ports:
            - "127.0.0.1:8443:8443"
            - "127.0.0.1:15023:15023"
        networks:
            - sechub
networks:
    sechub:
      name: sechub
