# SPDX-License-Identifier: MIT

spring:
  ssl:
    bundle:
      jks:
        pds-certificate:
          key:
            alias: ${PDS_SSL_KEYSTORE_ALIAS}
          keystore:
             # we use a configurable keystore location, e.g. "file:/var/server/certificate/prod-keystore.p12" 
            location: ${PDS_SSL_KEYSTORE_LOCATION}
            password: ${PDS_SSL_KEYSTORE_PASSWORD}
            type: ${PDS_SSL_KEYSTORE_TYPE}
            
server:
  ssl:
    bundle: "pds-certificate"
