# SPDX-License-Identifier: MIT

version: "3"
services:
    pds-tern:
        build:
            args:
                - BASE_IMAGE=debian:11-slim
            context: docker/
            dockerfile: Tern-Debian.dockerfile
        container_name: pds-tern
        #privileged: true
        env_file:
            - .env
        ports:
            - "127.0.0.1:8444:8444"
            - "127.0.0.1:15024:15024"
        networks:
            - "internal"
        volumes:
            - ./docker/scripts:/scripts
networks:
    internal:
