# SPDX-License-Identifier: MIT

# Main settings
server:
  port:
    4443
  ssl:
    enabled: true # always enabled
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
  
spring:
  messages:
    basename: "i18n/messages"
  profiles:
     group: 
        webui_dev: "webui_localserver"
        webui_test: "webui_test"
