# SPDX-License-Identifier: MIT

version: "3"
services:
  pds-owasp-zap:
    build:
      args:
        - BASE_IMAGE=debian:11-slim
      context: docker/
      dockerfile: Owasp-Zap-Debian.dockerfile
    container_name: pds-owasp-zap
    env_file:
      - .env
    networks:
      - "sechub"
networks:
  sechub:
    external: true
    name: "sechub"
