# SPDX-License-Identifier: MIT

version: "3"
services:
    pds_gosec_ubuntu:
        build:
            args:
                - BASE_IMAGE=ubuntu:focal
            context: docker/
            dockerfile: Dockerfile-Ubuntu
        container_name: pds_gosec_ubuntu
        env_file:
            - .env
        ports:
            - "127.0.0.1:8444:8444"
        networks:
            - "internal"
networks:
    internal:
