# SPDX-License-Identifier: MIT

replicaCount: 1

image:
    registry: "my.registry.example.org/pds_gosec"
    tag: "latest"

pds:
    startMode: localserver
    javaDebug:
        enabled: false
    keepContainerAliveAfterPDSCrashed: false

users:
    technical:
        id: "techuser"
    admin:
        id: "admin"

storage:
    type: "local"

database:
    enabled: false

networkPolicy:
    enabled: false

