# SPDX-License-Identifier: MIT
name: Build SecHub GitHub Action

on: workflow_dispatch

jobs:
  build-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Use Node.js
        # We do not define a dedicated node version here, we just use the default environment
        # which should be the default environment for the github actions runtime as well
        uses: actions/setup-node@v3 
    
      - name: Clean install
        run: npm ci 
        working-directory: ./github-actions/scan
        
      - name: Build
        run: npm run build --if-present
        working-directory: ./github-actions/scan
        
      - name: Run tests
        run: npm test
        working-directory: ./github-actions/scan
    
      